fastlane/Fastfile, fastlane/README.md
Get the 10 applications release status on AppStore Connect in the CLI.
The project have 5 AppStore Connect teams for each business units.
For each one, 2 builds, iOS and tvOS.
The idea is to get the Apple review status with one command line:
`bundle exec fastlane ios appStoreReleaseStatus`
=> Fastlane release status

Application/Sources/Content/ShowHeaderView.swift
Resolves #222 
Allow the tvOS user to read the full show description in the show page.
=> Expand text on tvOS show page

Application/Sources/Application/AppDelegate.m, Application/Sources/Helpers/RemoteCommandCenter.swift, PlaySRG.xcodeproj/project.pbxproj
Resolves #225 
SRF developer team found a workaround to keep the player alive enough when the background code ask to play a next convent in background.
Xcode Organizer view can help us to follow battery usage in next iterations. 
=> Keep player alive enough in background to play next content

Application/Sources/Bridges/PlaySRG-ObjectiveC.h, Application/Sources/CarPlay/CarPlay+Extensions.swift
Resolves #224 
Missing playlist when start playback with CarPlay.
=> Set recommended playlist to content playback with CarPlay

Application/Sources/Application/AppDelegate.m, Application/Sources/Model/Download+Private.h, Application/Sources/Model/Download.h, Application/Sources/Model/Download.m
Resolves #229.
For files already downloaded, the migration code run once, try to rename the file with the download url extension, if any.
Otherwise, it removes the file and the download item.
* Download few audio content fin Play RTS with a `develop` blanch build.
* Run this branch build. It runs the `updateUnplayableDownloads` method
* Downloaded audio content  can play again.
=> Update unplayable downloaded media

Application/Sources/Settings/Service.swift
The Zurich team works on a new backend and would like to test it. 
They will add end points in the future. for now, only `MediaComposition` and some `PAC` end points are implemented.
Example:
`xcrun simctl openurl booted "playsrf-debug://media/urn:srf:video:fadbc1b6-f613-4836-b8c8-65c39a2e42b9?server=sam%20test"`
- [] The branch has been rebased onto the `develop` branch.
=> Add SAM servers in settings

docs/RELEASE_CHECKLIST.md, fastlane/Fastfile, fastlane/README.md
Starting with [Xcode 14](https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes), Apple deprecated bitcode.
> Starting with Xcode 14, bitcode is no longer required for watchOS and tvOS applications, and the App Store no longer accepts bitcode submissions from Xcode 14.
- Uploading on AppStoreConnect does not create anymore dSYMs server side.
- The CI waits for dSYMs without any findings and skill after a while.  
- Remove asynchronous lane to download dSYMs from AppStoreConnect and upload its to AppCenter.
- Upload local dSYMs to AppCenter after the build and build upload to AppStoreConnect.
-  [ ] `swiftlint` has run to ensure the *Swift* code style is valid.
-  [ ] `rubocop -a` has run to ensure the *Ruby* code style is …
=> Fastlane builds ignore bitcode

Application/Resources/Apps/Play RSI/ApplicationConfiguration.json, Application/Resources/Apps/Play RTR/ApplicationConfiguration.json, Application/Resources/Apps/Play RTS/ApplicationConfiguration.json, Application/Resources/Apps/Play SRF/ApplicationConfiguration.json, Application/Sources/Configuration/ApplicationConfiguration.h, Application/Sources/Configuration/ApplicationConfiguration.m, TV Application/Sources/AppDelegate.swift, docs/REMOTE_CONFIGURATION.md
After review and tests of #246, separate iOS and tvOS live home sections order.
New remote configuration property added.
=> Scheduled livestreams sections for tv

Application/Sources/ProgramGuide/ProgramCell.swift
#249 TV program iteration reduced grid cell height. But the texts vertical alignement didn't follow correctly the Figma project.
- Vertical alignment for program texts in cells for the grid layout.
- Adjust right padding on list layout.
=> Alignment and padding adjustments for TV program grid and list layouts

Application/Sources/CarPlay/CarPlayTemplateListController.swift, Application/Sources/Configuration/PlayFirebaseConfiguration.m, Application/Sources/Content/PageViewModel.swift, Application/Sources/Content/SectionViewModel.swift, Application/Sources/Helpers/Signals.swift, Application/Sources/Search/SearchViewModel.swift
Resolves #181.
- Refresh content when entering in foreground after a while (1 minute).
- Updated remote configuration without launching the app, killing it, and reloading it.
=> Update page after a while and when configuration is updated

Application/Sources/Application/SceneDelegate.m, Application/Sources/Content/PageViewController.swift, Application/Sources/DeepLinking/DeepLinkAction.h, Application/Sources/DeepLinking/DeepLinkAction.m, docs/CUSTOM_URLS_AND_UNIVERSAL_LINKS.md
Following #246 , the need to deepking new livestreams content from web urls popped up.  
* Open the livestreams page: `[scheme]://livestreams`.
=> Livestreams tab deeplink

Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt, Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist, PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
Always try to be with latest version of third party libraires.
- Update patch dependencies
- Firebase to 10.2.0
- AirShip to 16.10.5
=> Update Firebase & AirShip dependencies

Makefile, fastlane/Fastfile
For SRG SSR testers, share more information when new beta versions are available.
- Slack the beta release notes with version and build number.
- Optional links to the internal Jira issues.
=> Notify in Slack new beta versions

Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt, Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist, Application/Sources/Content/Content.swift, Application/Sources/Content/PageViewController.swift, Application/Sources/Content/PageViewModel.swift, Application/Sources/UI/Views/HighlightCell.swift, PlaySRG.xcodeproj/project.pbxproj, PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
Resolves #267. 
Show promotion is a new layout.
Not yet deployed in production on Play PAC, only in IL Stage.
It also removes empty highlight (media) section, like Play web behavior.
=> Add show promotion representation and update highlight

Application/Sources/Application/Navigation.swift, Application/Sources/Helpers/AnalyticsClickEvent.swift, Application/Sources/ProgramGuide/ProgramViewModel.swift
Following #263 review with Android team, some missed events found.
Also a strange "start over" alert displayed too much times.
- Add `TVGuidePlayMedia` missing events if start over from te livestream.
- Update `TVGuidePlayLivestream` source for tvOS.
- Fix the start over alert, to be displayed only if the media has a resume playback position.
=> Program guide fixes

fastlane/Fastfile
After the Play iOS release https://github.com/SRGSSR/playsrg-apple/releases/tag/ios%2F3.6.10-406,
The Profile / Settings / What's new web view didn't select the "3.6.10" version as "installed version, but an old "3.6.1" version.
This issue appeared because of "3.6.10" version number. The Play iOS app is loading the web page with query parameters:
* the build number (build=406)
* the marketing version (version=3.6.10)
* the iOS version (iOS=16.2)
The What's new web page should select the correct version.
=> Fix build number used as div id on github pages

Application/Sources/Settings/SettingsViewModel.swift
Alignement with Android applications.
Discussions between native apps team members output: Get information when users use buttons in settings view:
- reset history
- reset favorites
- reset watch later media list
=> Add metrics on user content action in settings view

Application/Sources/Settings/SettingsViewModel.swift
Missing completion block in #276.
Fix this code feedback. Use completion block.
=> Code improvements on user content actions metrics in settings view

Application/Sources/Content/ShowHeaderViewModel.swift
Sadly, the analytics hidden events refactor #269 reintroduced a metric state issue.
Favorite add/remove and subscription add/remove are inverted.
=> Fix show header metrics

.rubocop.yml, fastlane/Fastfile
Switching to Ruby 3.1.3 has updated rubocop version as well.
Updated lint rules need to be respected.
Fix ruby files to run `rubocop -a` without warning.
=> Fix rubocop linter after ruby update

Application/Sources/Model/Mock.swift, Application/Sources/UI/Views/DownloadCell.swift, Application/Sources/UI/Views/DownloadCellViewModel.swift, Application/Sources/UI/Views/MediaCell.swift, Application/Sources/UI/Views/MediaVisualView.swift, Preview Content/Preview Assets.xcassets/Medias/SRGMedia_blocked.dataset/media-blocked.json, Preview Content/Preview Assets.xcassets/Medias/SRGMedia_fourFive.dataset/SRGMedia_fourFive.json, Preview Content/Preview Assets.xcassets/Medias/SRGMedia_fourThree.dataset/SRGMedia_fourThree.json, Preview Content/Preview Assets.xcassets/Medias/SRGMedia_minimal.dataset/SRGMedia_standard.json, Preview Content/Preview Assets.xcassets/Medias/SRGMedia_nineSixteen.dataset/SRGMedia_nineSixteen.json, Preview Content/Preview Assets.xcassets/Medias/SRGMedia_noShow.dataset/SRGMedia_noShow.json, Preview Content/Preview Assets.xcassets/Medias/SRGMedia_overflow.dataset/media-rts-tv.json, Preview Content/Preview Assets.xcassets/Medias/SRGMedia_rich.dataset/SRGMedia_rich.json, Preview Content/Preview Assets.xcassets/Medias/SRGMedia_square.dataset/SRGMedia_square.json, Preview Content/Preview Assets.xcassets/Medias/SRGMedia_standard.dataset/SRGMedia_standard.json
When media list is displayed verticality, the cell layout is horizontal, with a small image height than in grid or swimlane.
UX tests reported some readying difficulty with availability badge is display above the image in this case.
Availability badge should me on right side, with description texts.
- Move Availability badge (and livestream badge) for horizontal cell layout from image to right description texts.
- As VisualMediaView is used also for download cell, update both.
- Allow to display 3 lines for titles with horizontal cell layout.
=> Move availability badge for horizontal cell layout

fastlane/Fastfile
Fix regression introduced with #282.
`bundle exec fastlane iOS publishReleaseNotes` failed. A method parameter changed.
-  [ ] `swiftlint` has run to ensure the *Swift* code style is valid.
=> CI: fix release notes lane

Application/Resources/Apps/Play RTS/ApplicationConfiguration.json, Application/Sources/Configuration/ApplicationConfiguration.h, Application/Sources/Configuration/ApplicationConfiguration.m, Application/Sources/Content/ShowHeaderView.swift, Application/Sources/Content/ShowHeaderViewModel.swift, Application/Sources/Helpers/SRGShow.swift, Application/Sources/Model/FeaturedContent.swift, docs/REMOTE_CONFIGURATION.md
After #279, the show header view has now a turntable text view with a "more" action.
Play RSI has only show descriptions, Play SRF has short show leads and longer show descriptions.
Proposition is to display show description now, like Play web does.  
- A remote configuration added to prefer show leads. By default, it's prefer show descriptions.
- Applied this summary preference in show pages (displayed in the show header view).
- Applied this summary preference in the show element view.
- Renamed `LeadView` to `SummaryView` and fix unnecessary platform target.
Keep show lead only for Play RTS for now, like Play web.
-  [x] `rubocop -a` has run to ensure the *Ruby* code style is …
=> Better show description content

Application/Sources/UI/Views/TruncatableTextView.swift, TV Application/Sources/MediaDetailView.swift
Use same Text view component on SwiftUI view.
tvOS media detail view has a media summary view. 
- Replace the `Text` view with `TruncatableTextView`.
- Adapt with white foreground color.
=> Use truncatable text view on tvOS media detail view

Application/Sources/Application/AppDelegate.m, Application/Sources/Model/Download.m
Resolves #291.
- For files already downloaded, the migration code run once, try to rename the file with the download url extension, if any. Otherwise, it removes the file and the download item.
- For future downloads, it applies the downloaded url extension if any `octet-stream` content type extension returns by servers.
Similar as #230.
=> Update unplayable downloaded videos

docs/RELEASE_CHECKLIST.md, fastlane/Fastfile, fastlane/README.md
Beta tags are done by the CI, not AppStore release tags.
The goal is to run a fastlane on the CI to finish the git flow release started.
`afterAppStoreValidationGitFlow` lane:
- run on a `release/*` branch only.
- Find tags for iOS and/or tvOS platforms.
- Merge to `master` branch, apply tags.
- Merge first tag to `develop`branch.
- Bump marketing version and build number.
- Push `master`,  `develop` and tags to the origin.
Comment the 2 `push_to_git_remote` lines, to avoid last step.
=> CI: Do the git flow release finish with fastlane

fastlane/Fastfile
During the AppStore process release, check the translated What's new.
According to existing Fastlane lanes running in CI: https://github.com/SRGSSR/playsrg-apple/blob/develop/docs/RELEASE_CHECKLIST.md#fastlane-on-playcity-ci
- `iOSPrepareAppStoreReleases` and `tvOSPrepareAppStoreReleases` lanes adds what's new from Crowdin to AppStore Connect.
- What's new are displayed on the logs, but logs are on the CI.
Idea is to get in a manual lane, like `appStoreAppStatus`.
Fastlane `appStoreAppStatus` lane displays the upcoming "What's new" after the AppStore Connect state of latest version.
`fastlane iOS appStoreAppStatus`
=> CI: display what's new for latest version (appStoreAppStatus lane)

Application/Sources/Content/ShowHeaderView.swift
#279 introduces a beta feature.
If user tries with TestFlight distribution, but then go back to AppStore distribution, the layout must go back to production one.
Show header leading description padding keeps the user default settings, even if AppStore distribution is reinstalled.
- Fix the AppStore distribution with keeping the original leading description padding: use the Application setting function instead of user default (AppStorage) value.
=> Fix show header view layout updates with beta feature

Application/Resources/Apps/Play RSI/it.lproj/Accessibility.strings, Application/Resources/Apps/Play RSI/it.lproj/Localizable.strings, Application/Resources/Apps/Play RTR/rm.lproj/Accessibility.strings, Application/Resources/Apps/Play RTR/rm.lproj/Localizable.strings, Application/Resources/Apps/Play RTS/fr.lproj/Accessibility.strings, Application/Resources/Apps/Play RTS/fr.lproj/Localizable.strings, Application/Resources/Apps/Play SRF/de.lproj/Accessibility.strings, Application/Resources/Apps/Play SRF/de.lproj/Localizable.strings, Application/Resources/Apps/Play SWI/en.lproj/Accessibility.strings, Application/Resources/Apps/Play SWI/en.lproj/Localizable.strings, Application/Sources/UI/Views/TruncatableTextView.swift
The new #279 Show page header has a "show more" feature" with this label.
With Voice Over, the "more" in French should be pronounced "plus" with the "s".
Found by @svenduvoisin .
- Fix the prononciation for "more" for French VoiceOver.
- Update translation files (and keep beta test translations in English).
=> Pronunciation of "more" for accessibility in show page

Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt, Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist, PlaySRG.xcodeproj/project.pbxproj, PlaySRG.xcodeproj/xcshareddata/xcschemes/Play RSI TV.xcscheme, PlaySRG.xcodeproj/xcshareddata/xcschemes/Play RSI.xcscheme, PlaySRG.xcodeproj/xcshareddata/xcschemes/Play RTR TV.xcscheme, PlaySRG.xcodeproj/xcshareddata/xcschemes/Play RTR.xcscheme, PlaySRG.xcodeproj/xcshareddata/xcschemes/Play RTS TV.xcscheme, PlaySRG.xcodeproj/xcshareddata/xcschemes/Play RTS.xcscheme, PlaySRG.xcodeproj/xcshareddata/xcschemes/Play SRF TV.xcscheme, PlaySRG.xcodeproj/xcshareddata/xcschemes/Play SRF.xcscheme, PlaySRG.xcodeproj/xcshareddata/xcschemes/Play SWI TV.xcscheme, PlaySRG.xcodeproj/xcshareddata/xcschemes/Play SWI.xcscheme, PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
Resolves #299:
- on CI running on Mac OS Ventura: archives failed. No more nightly builds.
- on Xcode for developers running on Mac OS Ventura: some CoreData error displayed.
- User the new script from `SRGUserData` to avoid CoreData errors during compilation.
=> CI: xcodebuild archive succeeded on Mac OS Ventura

.swiftlint.yml
New SwiftLint version released 2 weeks ago: https://github.com/realm/SwiftLint/releases/tag/0.51.0
- Remove warnings.
- Add `period_spacing` and `duplicate_conditions` rules.
=> Update swiftlint to version 0.51.0

docs/README.md
Internal questions from colleagues about the supposed OS version. 
- Update minimum iOS 14.1.
- Add car emoji icon.
- Remove Tv emoji for Play SWI.
=> Tiny read me update

Application/Sources/Application/AppDelegate.m, Application/Sources/Application/Navigation.swift, Application/Sources/DeepLinking/DeepLinkAction.m, Application/Sources/Helpers/AnalyticsHiddenEvent.swift, Application/Sources/Player/MediaPlayerViewController.m, TV Application/Sources/LetterboxDelegate.swift
SRGSSR would like to reduce unique values for hidden event `value1` property.
- Remove value1 for continuousPlayback analytics event.
- Remove value1 for openUrl analytics event.
- Clean code.
=> Analytics cleanup

Application/Sources/Content/Content.swift, Application/Sources/UI/Helpers/ContextMenu.swift
Code review from `master`and `develop` branches, a property name was no longer understandable.
- Renaming.
=> Rename content section property

Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt, Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist, PlaySRG.xcodeproj/project.pbxproj, PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
#299 need an update from `SRGUserData`library. Use the official release.
- Update to SRGUserData 3.3.1.
=> Update SRGUserData to latest official version

Application/Sources/Helpers/Extensions.swift, Application/Sources/Helpers/SRGMedia.swift, Application/Sources/Model/FeaturedContent.swift, Application/Sources/UI/Helpers/MediaDescription.swift, Application/Sources/UI/Views/MediaCell.swift, Application/Sources/UI/Views/TruncatableTextView.swift, PlaySRG.xcodeproj/project.pbxproj
Following #306, @svenduvoisin and @Loic-Dumas found RSI content issue on the new show page on iPad:
- Description with empty lines.
- Media lead and description used differently on Play web and between application items (featured content, media detail page). 
- Prefer lead for media summary, fallback to description if lead is empty.
- Compact media summary in media cell (for iPad).
- Compact media summary in featured content section.
- Compact show summary in featured content section.
\* The project uses Github merge queue feature, which rebases onto the `develop` branch before …
=> Improve media and show summary on featured content and media cell 

Application/Resources/Apps/Play RSI/ApplicationConfiguration.json
A RSI user can share device support information to support team by email. 
- Add the local configuration for RSI.
=> Add RSI support mail

.swiftlint.yml, Application/Sources/Content/Content.swift, Application/Sources/Content/PageViewController.swift, Application/Sources/Content/PageViewModel.swift, Application/Sources/Content/SectionViewController.swift, Application/Sources/Content/SectionViewModel.swift, Application/Sources/Helpers/AnalyticsClickEvent.swift, Application/Sources/Helpers/AnalyticsHiddenEvent.swift, Application/Sources/Model/ServiceMessage.swift, Application/Sources/Onboarding/OnboardingViewController.swift, Application/Sources/ProgramGuide/ProgramCell.swift, Application/Sources/ProgramGuide/ProgramGuideDailyViewController.swift, Application/Sources/ProgramGuide/ProgramGuideDailyViewModel.swift, Application/Sources/ProgramGuide/ProgramGuideGridViewController.swift, Application/Sources/Search/SearchViewController.swift, Application/Sources/Search/SearchViewModel.swift, Application/Sources/Settings/Service.swift, Application/Sources/UI/Views/ImageView.swift, Application/Sources/UI/Views/LiveMediaCellViewModel.swift, TV Application/Sources/ExpandingCardButton.swift, TV Application/Sources/LabeledCardButton.swift
Following https://github.com/SRGSSR/pillarbox-apple/pull/365
The CI now uses SwiftLint 0.52.1 version.
- Update Swift code, according to the syntax improvements introduced in Swift 5.8 like implicit self in closures.
- Add new opt-in rules and update Swift code.
=> Update SwiftLint to 0.52.1

Application/Resources/Apps/Play RSI/ApplicationConfiguration.json, Application/Resources/Apps/Play RTR/ApplicationConfiguration.json, Application/Resources/Apps/Play RTS/ApplicationConfiguration.json, Application/Resources/Apps/Play SRF/ApplicationConfiguration.json, Application/Resources/Apps/Play SWI/ApplicationConfiguration.json
A SRF user reported  than the code source url in application settings returns 404.
Remote configuration had the old github urls: https://github.com/SRGSSR/playsrg-ios
Github stopped the redirection after a while.
Remote configuration is now updated. Local configuration could be updated as well.
- Add local configuration for source code url.
=> Add local configuration for source code url

docs/PUSH_NOTIFICATIONS.md
Tiny improvement in the Push notification documentation.
- Split AirShip  _Content_ step in more detail sections and bullet points.
- Update basic push notification behavior.
=> Improve push notification documentation

Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt, Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist, PlaySRG.xcodeproj/project.pbxproj, PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
The new SRF VoD/AoD streaming packaging solution is deployed and SRF VoD with segments can't be played anymore.
https://github.com/SRGSSR/srgletterbox-apple/releases/tag/9.0.0 did an update to fix it client side.
> New SRF VoD/AoD streaming packaging solution uses server side Akamai token.
> The token is in a query parameter `hdnts` is delivered by server, Integration Layer.
> Letterbox url added an additional parameter `__b__` for start bitrate in the previous streaming packaging solution.
> Letterbox encoded the query parameter, but the streaming package solution does not accept it: 403 on HLS manifest.
- Update to Letterbox 9.0.0, which removed the encoded query parameters step.
- The branch should be rebased onto the `develop` branch for whole tests with nighties, but it's not …
=> Update Letterbox dependency to 9.0.0

Application/Sources/MiniPlayer/PlayMiniPlayerView.m
On old devices, some user feedbacks shared that the sound continue to be played after a while, after closing the mini player.
- Call stop on the player when closing the mini player.
=> Stop player quicker when closing mini player

Makefile, Scripts/spm-outdated.sh
Updating SPM dependencies with Xcode only take care with the version rules defined (next major, next minor, branch, commit hash).
https://github.com/kiliankoe/swift-outdated can help developer to be notify of all new updates.
Thanks @defagos to shared this tool.
- Add `spm-outdated` make command.
=> Add spm-outdated make command to check SPM dependencies

fastlane/Fastfile
Fastlane code update for branch beta #339 creates a regression for nighties information on CI:
The build number from the nighties is not displayed anymore.
Fix it.  
- When build number is override for nighties, notify the CI.
=> CI: update version notification to CI with nighty build number

Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt, Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist, Application/Sources/UI/Views/PlayNavigationView.swift, PlaySRG.xcodeproj/project.pbxproj, PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
Following library dependency, SwiftUI-Introspect version is now updated to latest one.
- Update SwiftUI-Introspect dependency to 0.9.1
- On iOS targets, replace the deprecated method from `Introspect` framework to new `introspect(:,on:)` method in `SwiftUIIntrospect` framework.
- On tvOS targets, remove `Introspect` framework and `PlayNavigationView.swift`.
=> Update SwiftUI-Introspect dependency to 0.9.1

Application/Sources/Configuration/PlayFirebaseConfiguration.m
Check out the project. Just run cocoa pods and no access to the private configuration repository, I can build the project for a personal investigation, as it's a public project. 
- Don't start Firebase if not configured at launch.
=> Don't start Firebase if not configured

Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt, Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist, PlaySRG.xcodeproj/project.pbxproj, PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
AppCenter diagnostics reported few crashes on all BU iOS apps.
Update libraries which have fixes.
- SRGMediaPlayer 7.2.0: https://github.com/SRGSSR/srgmediaplayer-apple/releases/tag/7.2.0
- SRGLetterbox 9.1.0: https://github.com/SRGSSR/srgletterbox-apple/releases/tag/9.1.0
- Update SRG libraries to official releases as well.
=> Fix some iOS player crashes

fastlane/Fastfile
Since days, the dSYM upload failed with a 503 error and an exception is raised.
See https://github.com/microsoft/fastlane-plugin-appcenter/issues/322.
It stops the CI script.
Proposition is to be resilient to App Center sever issue.
- Catch App Center upload error.
- Copy locally the dSYM zip file if error occurred.
=> CI: Don't failed because of App Center upload

Application/Resources/Apps/Play RTR/ApplicationConfiguration.json
Play RTR data protection url did not open correct page anymore.
Update the local configuration for `dataProtectionURL`.
=> Update RTR data protection url

Application/Resources/Apps/Play RSI/it.lproj/Localizable.strings, Application/Resources/Apps/Play RTR/rm.lproj/Localizable.strings, Application/Resources/Apps/Play RTS/fr.lproj/Localizable.strings, Application/Resources/Apps/Play SRF/de.lproj/Localizable.strings, Application/Resources/Apps/Play SWI/en.lproj/Localizable.strings, Application/Sources/Application/AppDelegate.m, Application/Sources/Content/SectionViewController.swift, Application/Sources/Content/SectionViewModel.swift, Application/Sources/Settings/ApplicationSettings.h, Application/Sources/Settings/ApplicationSettings.m, Application/Sources/Settings/ApplicationSettingsConstants.h, Application/Sources/Settings/ApplicationSettingsConstants.m, Application/Sources/Settings/SettingsView.swift, Application/Sources/Settings/UserDefaults+ApplicationSettings.swift, Application/Sources/UI/Views/MediaCell.swift
#306 introduced a beta setting option to test divider on the vertical media list.
Options moved from public beta to internal beta.
Tests ended and options can be removed.
- Remove setting.
- Remove style and views related to divider.
=> Remove divider beta setting option

Application/Resources/Apps/Play RTR/rm.lproj/Localizable.strings
RTR colleagues updated romansh translations. 
- Ran private script `./Configuration/Scripts/pullCrowdin.sh`.
=> Update romansh translation

fastlane/Fastfile
Get iOS tag the latest on Github UI.
- Apply first tvOS tag, then iOS tag.
=> CI: Tag tvOS first, then iOS

.github/release.yml
Github release note can be autogenerated when creating it. Customisation is possible, linked to labels:
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
- Add yml file for GitHub release notes.
=> Customise Github automated release notes

Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt, Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist, PlaySRG.xcodeproj/project.pbxproj, PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
See #336. Letterbox player could hide the seek control on iOS when opened from the mini player.
- Update Letterbox to version 9.1.2: https://github.com/SRGSSR/srgletterbox-apple/releases/tag/9.1.2
=> Update Letterbox for iOS 17 support

Application/Sources/Application/UserConsentHelper.swift, UITests/Screenshots/Resources/Apps/Play RTS/Configuration.plist, UITests/Screenshots/Sources/Helpers/SnapshotHelper.swift, fastlane/Fastfile, fastlane/Snapfile
The last Play RTS screenshot for AppStore is the search view. The term needs an update.
RTS TV channel logos are updated on 21.08.2023, screenshots should be updated.
- Update Play RTS target configuration file with new search term. 
- Update Fastlane Screenshot helper, outdated.
- Update `deliver` parameters to ignore language when uploading screenshots: only on language is enabled, `fr-FR`, but device screenshots are `fr-CH`.
TBD:
- Check why `override` can't delete screenshots anymore.
- Fix it if possible.
\* The project uses Github merge queue feature, which rebases onto the …
=> Update screenshot script to avoid user consent banner

docs/RELEASE_CHECKLIST.md, fastlane/Fastfile, fastlane/README.md
SRF marketing team did great tvOS AppStore image preview for the AppStore detail page.
The fastlane script must not erase it now.
- Remove the upload screenshots step in script.
=> CI: don't erase existing Play SRF tvOS screenshots

fastlane/Fastfile
Running in parallel the iOS and tvOS private betas workflow, the [second workflow](https://playcity.eu.ngrok.io/buildConfiguration/playsrgios_BetasIOS/387008?buildTab=log&focusLine=16791&logView=flowAware&linesState=103) ended with an error.
```
push_to_git_remote
* [new tag]           ios/3.7.8-430 -> ios/3.7.8-430
! [rejected]          develop -> develop (non-fast-forward)
error: failed to push some refs to 'github.com:SRGSSR/playsrg-apple.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
- change action on tags step to …
=> Fix fastlane private betas workflow

Application/Resources/Apps/Play RTR/ApplicationConfiguration.json, Application/Sources/Configuration/ApplicationConfiguration.h, Application/Sources/Configuration/ApplicationConfiguration.m, Application/Sources/Settings/ApplicationSettings+Common.h, Application/Sources/Settings/ApplicationSettings+Common.m, Application/Sources/Settings/ApplicationSettings.h, Application/Sources/Settings/ApplicationSettings.m, Application/Sources/Settings/ApplicationSettingsConstants.h, Application/Sources/Settings/ApplicationSettingsConstants.m, docs/REMOTE_CONFIGURATION.md
As a RTR user, I want to have the German subtitle active the first time, so that I can easy read what is spoken in Rätoromanisch.
Many RTR videos have German subtitles included, in the HLS manifest.
First time, enable German subtitles if the video has it. Let the user decide after to keep it or disable it.
- Add `discoverySubtitleOptionLanguage` remote configuration to enable subtitles in the selected language at first time a video with subtitles is played.
- To keep this setting on next video, apply the language choice on the system level.
- Save in User Default that it has been run one. No more execution after.
- Set `discoverySubtitleOptionLanguage` to `de` for Play RTR.
- …
=> Enable subtitles first time for Play RTR

Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt, Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist, PlaySRG.xcodeproj/project.pbxproj, PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
Data engineer would like to restore device language information.
https://github.com/SRGSSR/srganalytics-documentation/issues/8 
- Update SRGAnalytics which have a Commanders Acts SDK update: https://github.com/SRGSSR/srganalytics-apple/releases/tag/9.0.1
=> Update SRGAnalytics with language and region

Application/Sources/Application/UserConsentHelper.swift
Building `AppStore` configuration on simulator, no Airship configuration is founded.
The application crashes at launch.
This PR fixes it. 
- Apply AirShip consent only if AirShip instantiated.
=> Fix build with no Airship configuration

Application/Sources/Application/AppDelegate.m, Application/Sources/Application/Navigation.swift, Application/Sources/Helpers/Categories/UIViewController+PlaySRG.m, Application/Sources/MiniPlayer/PlayMiniPlayerView.m, Application/Sources/Player/MediaPlayerViewController.m, Application/Sources/Player/MediaPreviewViewController.m, Application/Sources/Player/SongsViewController.m
UX feedbacks after 1 month with the user consent banner:
- Siri shortcut can't play audio automatically content if banner is displayed.
- Playing video in Picture in Picture and displaying user consent second banner from the settings view pause the content.
Strange for the users.
- Don't stop playback because of user consent banner displayed.
=> Don't stop playback because of displayed user consent banner

Application/Sources/Settings/SettingsView.swift
As a tester at SRGSSR, they need to check the app version often.
The natural UX is to open the application settings view and scroll down.
For debug, nighty and private beta builds, additional settings sections are displayed, and application version information is not at the bottom.
This PR proposes to add application version at bottom on any builds, if not displayed.
- Add application version in an additional information section at below of the settings view for debug, nighty and private beta builds, after the advanced sections.
\* The project uses Github merge queue feature, which …
=> Application version at bottom settings view on any builds

Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt, Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist, PlaySRG.xcodeproj/project.pbxproj, PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
See https://github.com/SRGSSR/srgletterbox-apple/releases/tag/9.2.1.
The linked PR for more detail: https://github.com/SRGSSR/srgletterbox-apple/pull/310
- Update `SRGLetterbox` to 9.2.1 version.
=> Update SRGLetterbox with skip gestures improvement

Application/Sources/ProgramGuide/ProgramPreviewModel.swift
On tvOS big screen, the program images are usually blurred.
It's use the medium resolution.
Using large takes a bit more time to download it but the image has a better quality.
- Use `.large` image url for tvOS program images.
=> Better image resolution on tvOS program guide

Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt, Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist, Application/Sources/Helpers/Extensions.swift, PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
Fix device language and region properties
The current Commanders Act SDK 5.4.1 added `context.device.language` and `context.device.region` properties.
But the values are the application values, not the device values.
https://github.com/CommandersAct/iOSV5/issues/11 fixes it.
- Update Commanders Act SDK to this patch release 5.4.2: https://github.com/CommandersAct/iOSV5/releases/tag/5.4.2
- Remove `navigation_device_language` custom global label. https://github.com/SRGSSR/srganalytics-documentation/issues/8
\* The project uses Github merge queue feature, which rebases onto the …
=> Update Commanders Act to 5.4.2

Application/Sources/Application/AppDelegate.m, Application/Sources/Helpers/Extensions.swift, TV Application/Sources/AppDelegate.swift
#326 and #387 introduced Commanders Act v5.x update.
From v4 to v5, the unique id property changed.
The current version 5.4.2 introduced ServerSide method `useLegacyUniqueIDForAnonymousID()`.
Not enough to still in use `TC_UNIQUEID` value in the new `context.device.sdk_id` new used property.
A manual migration as to be done, before a fix is implemented in SRGAnalytics and / or Commanders Act SDK.
Related links:
- Commanders Act SDK discussion https://github.com/CommandersAct/iOSV5/issues/13.
- Commanders Act SDK properties documentation: https://doc.commandersact.com/developers/tracking/about-events/mobile-sdk-event-specificity
- ~Apply once a copy of the `TC_UNIQUEID` value in `tc_unique_id` property to `#TC_SDK_ID#` property in User Default used for _device.sdk_id_ property in all event …
=> Patch analytics migration

docs/RELEASE_CHECKLIST.md
Our team missed the Jira release date, which close the release on Jira.
- Add the step in the checklist template, which is copied on a spreadsheet  tool internally.
=> Release checklist: Add Jira release step

Application/Resources/Apps/Play RTS/fr.lproj/Localizable.strings
In the TV Guide, the calendar alert has a French translation issue.
Translators fixed it.
- Update French translations.
=> Fix french translation

Application/Sources/Content/ShowHeaderViewModel.swift, Application/Sources/Favorites/Favorites.m, Application/Sources/Helpers/ApplicationSectionInfo.m
RTS case studies had users during one week. New users didn't found notifications and share interest to get new content (page 41 and 44).
One proposition should be to display more offend the bell icon, which is the subscribe button for a show and get new on demand episodes.
- Always display subscribe button on iOS show page and add show to favorite if subscription enabled.
- Always display notifications button on iOS profile page so that user knows that the application support notifications.
\* The project uses Github merge queue feature, which rebases onto the `develop` branch …
=> Always display subscribe buttons on iOS

Application/Resources/Apps/Play RSI/ApplicationConfiguration.json, Application/Resources/Apps/Play RTR/ApplicationConfiguration.json, Application/Resources/Apps/Play RTS/ApplicationConfiguration.json, Application/Resources/Apps/Play SRF/ApplicationConfiguration.json, Application/Resources/Apps/Play SWI/ApplicationConfiguration.json, Application/Sources/Application/AppDelegate.m, Application/Sources/Configuration/ApplicationConfiguration.h, Application/Sources/Configuration/ApplicationConfiguration.m, Application/Sources/Configuration/ApplicationConfiguration.swift, Application/Sources/Configuration/PlayFirebaseConfiguration.h, Application/Sources/Configuration/PlayFirebaseConfiguration.m, Application/Sources/Configuration/TVChannel.h, Application/Sources/Content/Publishers.swift, Application/Sources/Helpers/ProgramAndChannel.swift, Application/Sources/Model/Mock.swift, Application/Sources/ProgramGuide/ProgramCell.swift, Application/Sources/ProgramGuide/ProgramCellViewModel.swift, Application/Sources/ProgramGuide/ProgramGuideDailyViewController.swift, Application/Sources/ProgramGuide/ProgramGuideDailyViewModel.swift, Application/Sources/ProgramGuide/ProgramGuideGridViewController.swift, Application/Sources/ProgramGuide/ProgramGuideHeaderView.swift, Application/Sources/ProgramGuide/ProgramGuideViewModel.swift, Application/Sources/ProgramGuide/ProgramPreview.swift, Application/Sources/ProgramGuide/ProgramView.swift, Application/Sources/ProgramGuide/ProgramViewModel.swift, docs/REMOTE_CONFIGURATION.md
Play SRG apps are BU (business unit) centric, for their content and languages.
In the TV program guide, #239 and previous commit introduced bouquets for BU channels and Third party channels, used in Play SRF.
Users asked to also have other RSI and RTS TV channel programs, as Play web have and other TV guide services.
Goal is to add it with a correct UX.
- Introduce remote configuration `tvGuideOtherBouquets` to list other channel bouquets to display, after the vendor bouquet.
- During the content loading of the TV guide, the logic is updated:
- first publisher loads the BU channel programs, an second publisher loads other channels from other bouquets.
- `SRGChannel` is replaced by `PlayChannel` in publishers to share if the channel is "SRG" or external. 
- Other BU media and show can be …
=> TV program guide with all SRG vendors

Makefile
The project uses [Crowdin](https://crowdin.com) service for translations.
API need to be updated. Effective from November 30, 2023, the current used API v1 will no longer be supported.
- Use updated script from private configuration. https://github.com/SRGSSR/playsrg-apple-configuration/pull/3
=> Update translation pulling script

Makefile, Scripts/pullCrowdin.sh, crowdin.yml, docs/README.md, docs/RELEASE_CHECKLIST.md, fastlane/Fastfile
Pulling translations script is in the private repository since a long time.
Moving it to the public repository and hide the api token only in this private repository.
Help developers with a `Makefile` command.
This PR follows #395 and #397.
- Add `Scripts/pullCrowdin.sh` which pull PlaySRG and SRGLibraries translations from crowdin.com
- Update fastlane script. Translations used for publication on AppStore and What's new notes on the GitHub page.
- Simplify with `make pull-translations` command line.
- Update configuration to have crowdin api token. https://github.com/SRGSSR/playsrg-apple-configuration/pull/5
- The code followed the code style as `make quality` passes with a …
=> Add make pull-translations

Application/Sources/ProgramGuide/ProgramViewModel.swift
Following the multi BU channels in TV guide #389 , the default sharing url using not the best vendor shared url.
Also, on a livestream event, the default Play home url was not interesting. Try to share the livestream url wherever the program is available.
- Share the default Play url, regarding the channel vendor, not the application vendor. 
- ~Share the livestream url wherever the program is available.~
=> Improve TV guide shared url in calendar event

docs/REMOTE_CONFIGURATION.md
#389 added a new remote configuration property. One of the value described in the documentation file has a not expected space character.
- Remove the not expected character.
=> Fix documentation

fastlane/Fastfile, fastlane/README.md
Public beta versions helps the project to have more user testing the applications, with just using the applications. Analytics, crashlogs, feedbacks if really there is an issue.
As a developer we needs to submit the build to a TestFlight app review, for the first build of a new version. It's take between 24 and 48 hours, and usually 100% validated.
Like the fastlane `appStoreAppStatus`, propose a `appStoreTestFlightAppStatus` lane.
- Get TestFight groups and their builds.
- Get builds information and status for the latest versions.
- Match the two informations and displays status. 
- Scope is only Public AppStore builds of the latest known version. (not previous versions, not private betas or nighties).
- The branch should be rebased onto the `develop` branch for whole tests with …
=> Fastlane: add AppStore TestFlight app status lane

Application/Sources/Player/MediaPlayerViewController.m
The updated TV program guide displays now all SRG TV channels, thanks to #389 proposition. For consistency in the code, check that media detail view support other channel vendor.
- Request radio livestreams is updated to use channel vendor instead of application vendor.
=> Request radio livestreams with channel vendor

Application/Resources/Apps/Play RTS/ApplicationConfiguration.json
Play web has in in search options, "subtitles available" for Play RTS:
https://www.rts.ch/play/recherche?query=&showAll=true&properties=subtitlesAvailable
Missing in Play RTS iOS.
- Update the remote and local configuration for Play RTS.
=> Enable search subtitles available option for Play RTS iOS

Application/Sources/Content/PageViewController.swift
On a show page, media cells don't need to display the show title again, as it's displayed in the show header and navigation bar.
#390 introduced content swimlane sections, like on homepages and topic pages but does not respect the show page rule.
- Don't display show title in subtitle label on media cells in show pages.
=> Use date style on swimlane media cells for show page

Application/Sources/Content/PageViewModel.swift
On content pages, if a section request returns an error, the placeholders items stay.
It's create a stream UI and not understable.
Like Play web and recent Play Android fix, remove placeholders items if request failed.
Current example: La chronique scientifique - https://www.rts.ch/play/radio/quicklink/9929109
- Error on a section request returns the cached responses, or empty row, not more placeholders.
=> No placeholders if section errors

Application/Sources/Content/PageViewController.swift, Application/Sources/Model/FeaturedContent.swift, Application/Sources/UI/Views/FeaturedContentCell.swift, Application/Sources/UI/Views/FeaturedDescriptionView.swift
Following "Use date style on swimlane media cells for show page" #412, this PR missed media element.
- Remove show title everywhere on a show page when media is from the same show.
=> Don't display show title on show page everywhere

Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt, Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist, Application/Sources/Application/AppDelegate.m, Application/Sources/Helpers/Extensions.swift, PlaySRG.xcodeproj/project.pbxproj, PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved, TV Application/Sources/AppDelegate.swift
A player feature named "kill switch" was introduced [in 2017](https://github.com/SRGSSR/srgletterbox-apple/commit/c9a2910d21fcb4ce364813e9a741bf93a00fc286) for legal reason. https://github.com/SRGSSR/srgletterbox-apple/releases/tag/1.6
Since few months, users reported unexpected stops during video on demand playbacks.
Player team investigated is because of this player feature: https://github.com/SRGSSR/pillarbox-documentation/issues/51
A new player release removes this feature, thanks to our users.
- Update `SRGLetterbox` to version [9.3.0](https://github.com/SRGSSR/srgletterbox-apple/releases/tag/9.3.0).
- Update `SRGAnalytics` to version [9.1.0](https://github.com/SRGSSR/srganalytics-apple/releases/tag/9.1.0).
- Remove #388 .
- The branch should be rebased onto the `develop` branch for …
=> Remove unexpected playback stops 

Application/Sources/Configuration/ApplicationConfiguration.swift
The application can run on a Mac with an Apple chipset.
The platform could be `desktop` instead of `tablet` for the feedback form.
Inspired by https://github.com/SRGSSR/srganalytics-apple/pull/83 and https://github.com/SRGSSR/pillarbox-apple/pull/364.
- Update feedback type implementation with `ProcessInfo` to set `desktop` value.
=> Add desktop type for feedback form

Application/Sources/UI/Controllers/PageContainerViewController.swift
The following last swift conversion #430 introduced `!` on controller view properties.
A rotation on iPad calls `viewWillTransition(to:with:)` even the view is not loaded.
- Fix with a test condition.
=> Fix rotation crash on iPad

PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
The third parts SDK for user consent as been updated and now it saves the user choices per configurations.
Applications have two configurations, CH and WW.
- Update UserCentrics to version [2.12.0](https://usercentrics.com/docs/apps/releases/).
=> Reduce display of user consent banner when travelling outside Switzerland

Application/Resources/Apps/Play RSI/it.lproj/Localizable.strings, Application/Resources/Apps/Play RTR/rm.lproj/Localizable.strings, Application/Resources/Apps/Play RTS/ApplicationConfiguration.json, Application/Resources/Apps/Play RTS/fr.lproj/Localizable.strings, Application/Resources/Apps/Play SRF/ApplicationConfiguration.json, Application/Resources/Apps/Play SRF/de.lproj/Localizable.strings, Application/Resources/Apps/Play SWI/en.lproj/Localizable.strings, Application/Sources/Configuration/ApplicationConfiguration.h, Application/Sources/Configuration/ApplicationConfiguration.m, Application/Sources/Helpers/Categories/UILabel+PlaySRG.h, Application/Sources/Helpers/Categories/UILabel+PlaySRG.m, Application/Sources/Helpers/Extensions/DateFormatter+playSRG.swift, Application/Sources/Helpers/Extensions/UIColor+PlaySRG.swift, Application/Sources/Model/FeaturedContent.swift, Application/Sources/Player/MediaPlayerViewController.m, Application/Sources/Player/MediaPlayerViewController.storyboard, Application/Sources/UI/Helpers/MediaDescription.swift, Application/Sources/UI/Views/Badges.swift, Application/Sources/UI/Views/DownloadCell.swift, Application/Sources/UI/Views/FeaturedDescriptionView.swift, Application/Sources/UI/Views/HeroMediaCell.swift, Application/Sources/UI/Views/LiveMediaCellViewModel.swift, Application/Sources/UI/Views/MediaCell.swift, TV Application/Sources/MediaDetailView.swift, Translations/Localizable.strings, docs/REMOTE_CONFIGURATION.md
After user tests, update badges color.
Align with the Play SRG web version. 
- Update badges colors:
- Update web first badge color to dark red.
- Update upcoming badge color to black.
- Update featured badge color to dark red.
- Change badge font to lowercase.
- Remove "soon" badge in media detail pages.
- [Transition] Add remote configuration `webFirstBadgeEnabled` property to display the web first badges on media items.
- Around badges:
- Remove duplicate date and time when upcoming badge is displayed (media items, media detail pages). ie like upcoming livestream events.
- Replace web first future date with "in advance" text.
- In vertical list, media item can display 3 lines for titles, with a badge and no subtitles.
- Cleanup `MediaDescription` and expose it to Objective-C code so …
=> Update badge concepts

Application/Sources/Content/Content.swift, Application/Sources/Content/PageViewModel.swift
Testing #431 across BU builds, the page can be load, but not the content.
Like Play web and Play Android, use the object vendor when available instead of the application configured vendor.
For requests, if available:
- Use content vendor (page and section).
- Use show vendor.
- Use topic vendor.
=> Use object vendor for requests

Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt, Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist, PlaySRG.xcodeproj/project.pbxproj, PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
Use an official release of `SRGDataProvider`.
- Update `SRGDataProvider` to version [19.0.1](https://github.com/SRGSSR/srgdataprovider-apple/releases/tag/19.0.1).
=> Update DataProvider dependency

Application/Sources/Content/Publishers.swift, Application/Sources/Helpers/Extensions/SRGMedia+PlaySRG.swift
**As** a user who added shows to my favorites
**I want** to see on homepage latest published episodes from the web publication date, not broadcast date
**so that** I don’t have “web first” episodes days or weeks in first elements displayed in my user media list swimlane.
- Set a `publicationDate` for media: `media.startDate` if exists, otherwise `media.date`.
- For the “my program” content section, sort episodes with this descending `publicationDate`, instead of the descending `media.date`.
\* The project uses Github merge queue feature, which rebases onto the `develop` branch …
=> Sort user latest episodes by web publication date

Xcode/Shared/BUs/RSI.xcconfig, Xcode/Shared/BUs/RTR.xcconfig, Xcode/Shared/BUs/RTS.xcconfig, Xcode/Shared/BUs/SRF.xcconfig, Xcode/Shared/BUs/SWI.xcconfig
To test Apple universal links, iOS builds needs a domain with can answer to `.well-known/apple-app-site-association`.
For easier tests with web urls, connect `Debug`, `Nightly` and private `Beta` to Play web non production version. Thanks to https://github.com/mmz-srf/play-web/pull/1251.
- Update `BU__DOMAIN` for `Debug`, `Nightly` and private `Beta` build configurations.
=> Connect non-production builds to Play web staging domain

Application/Sources/RadioChannels/RadioChannelsViewController.swift, Application/Sources/UI/Controllers/PageContainerViewController.swift
Following Swift conversion #430 , some crashes appeared.
This PR would like to fix #440.
- Remove forced unwrap values.
- Check that the `pageViewController` view is loaded, otherwise, update the `initialPage` index. 
=> Crash when opening audio channel view from media player view

Application/Sources/UI/Helpers/MediaDescription.swift, TV Application/Sources/MediaDetailView.swift
Following Swift conversion #430 , some crashes appeared.
This PR would like to fix #444.
- Support optional Media parameter on the two `MediaDescription` methods used by the objective-C code.
=> Support optional media from iOS media player view

Application/Resources/PrivacyInfo.xcprivacy, PlaySRG.xcodeproj/project.pbxproj, TV Application/Resources/PrivacyInfo.xcprivacy
Apple introduced a new warning when submitting build on AppStoreConnect.
The warning explains that the build needs to include the `PrivacyInfo.xcprivacy` manifest file and declare the access API usage.
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files
- Add `PrivacyInfo.xcprivacy` manifest file, one for iOS and one for tvOS builds.
- For iOS, support User Defaults and Disk Space API accesses.
- For tvOS, support User Defaults access API access.
\* The project uses Github merge queue feature, which rebases onto the `develop` branch before squashing and …
=> Privacy info manifest

Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt, Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist, PlaySRG.xcodeproj/project.pbxproj, PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
All image urls can now use Play SRG image service, RTS image included.
RTS service image has been updated to support the _aspect ratio_ sub path without _width_ or _height_ requested values.
https://github.com/SRGSSR/srgdataprovider-apple/issues/47
- Update `SRGDataProvider` with this fix: https://github.com/SRGSSR/srgdataprovider-apple/pull/51
=> Update SRGDataProvider with RTS image service update

PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
Xcode 15.3 now uses Swift Package Manager version 3 and an `originHash` hash.
- Update `Package.resolved` file with Xcode 15.3 constraint.
=> Update Swift Package Manager to version 3

.github/workflows/pr-closure.yml, .yamllint.yml
The CI can now shared deployment with #447.
When a PR si closed, the GitHub branch is deleted.
Like [Play web deployments](https://github.com/mmz-srf/play-web/deployments), the PR merge is set inactive the deployment.
- Add a Github action to fallow PR closure and update the latest deployments for iOS and tvOS nighties.
- Take care of "playsrg-beta" and "playsrg-testflight" environments. They should not have brand environments.
=> Deployment status updated after PR closure

fastlane/Fastfile
Following #447 and the first private and public betas ([iOS](https://github.com/SRGSSR/playsrg-apple/releases/tag/ios%2F3.8.5-449) and [tvOS](https://github.com/SRGSSR/playsrg-apple/releases/tag/tvos%2F1.8.5-449)), the environment urls for private betas are wrong. Because of the bump build number commit during the workflow.
The deployment ref are links to the branch and could be links to the tag for more readiness.
- Add tag support for GitHub deployment creation.
- Fix the environment urls for betas.
- Replace GitHub deployment for betas if new tag is created during the workflow with one with tag as a ref. 
- The code followed the code style as `make quality` passes with a …
=> Improve beta Github deployments

Application/Sources/Helpers/Extensions.swift
> It looked like a mistake if the navigation starts with `#0-9` in the "A to Z" view. Also if a user navigates with a screen reader (like VoiceOver), it's easier to understand at the end of the navigation.
The show list should start with “A” section. And “#“ should be at the end of the list.
- Move "#" section to the end of the AZ list (in Videos and Audios).
=> Move # section to end of AZ list (PLAYRTS-5499)

fastlane/Fastfile
Jira displays the deployment task name. Default is `deploy` but [it can be updated](https://docs.github.com/en/rest/deployments/deployments?apiVersion=2022-11-28#create-a-deployment).
Related to #447.
- Update deployment task and description.
=> Rename Github deployment task

Application/Resources/PrivacyInfo.xcprivacy, TV Application/Resources/PrivacyInfo.xcprivacy
Some new emails from Apple are reported for the tvOS builds.
We missed them from #443.
Which code or library include in both iOS and tvOS build use disk space?
Not sure but maybe [YYWebImage dependency from Letterbox](https://github.com/SRGSSR/srgletterbox-apple/blob/fa32959d7899e5002a313a667876cf4265ece9b1/Package.swift#L27), as some cache disk API exists.
- Add Disk Space API accesses to tvOS.
- Update Disk Space API accesses reason for iOS.
=> Privacy info manifest update (PLAYRTS-5489)

fastlane/Fastfile
Following #458 and new `stopUnfinishedGithubDeployments` lane introduction, TeamCity had a build number override.
It does not displayed the correct build number for nightlies.
- Don't notify CI for github deployments lane.
=> Fix CI build number notification for nightlies

docs/GITHUB_ENVIRONMENTS_AND_DEPLOYMENTS.md, docs/RELEASE_CHECKLIST.md, fastlane/Fastfile, fastlane/README.md
After #447 implementing non-production environment deployments, adding the AppStore distribution as a production environment deployments is one next step.
Not sure when is useful on GitHub pages for now, it's useful for [Jira deployment view](https://support.atlassian.com/jira-cloud-administration/docs/what-is-the-deployments-feature/).
Proposition is to use the `appStoreAppStatus` lane which is already check the AppStore Connect states. Add an option to manage GitHub production deployments.
`bundle exec fastlane ios appStoreAppStatus github_deployments:true`
Additional documentations:
- App Store Connect state: https://github.com/fastlane/fastlane/blob/df12128496a9a0ad349f8cf8efe6f9288612f2cb/spaceship/lib/spaceship/connect_api/models/app_store_version.rb#L31
-  Add `github_deployments` …
=> Github production deployments

fastlane/Fastfile
Topic: #447.
AppStoreBuilds and TestFlight public distributions not work as expected with #464.
Only tag deployments should be used if scripts runs on the tagged commit.
Investigate and fix it.
- Fixing the `sh` command. It returned a breaking line, which brake the commit _sha_ comparaison.
=> Fix Beta and TestFlight tag Github deployments

.github/workflows/pr-closure.yml, docs/GITHUB_ENVIRONMENTS_AND_DEPLOYMENTS.md
Topic: #447.
The #449 PR added a GitHub action to update deployment state to inactive.
It was only for the nightly iOS and tvOS branches environments.
The proportion is to add beta branches environments in the list of state updates.
- Update bash script to support iOS and tvOS beta branches environments.
=> Update branch beta GitHub environments to inactive state

.issuetracker
The project information can be found in issue / PR on the open source GitHub repository, but also in the closed Jira project at SRGSSR.
We can share the issue tracker configuration for new colleagues. 
- add the shared `.issuetracker` file, created by [Fork Mac app](https://fork.dev).
=> Add shared issue tracker configuration

Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
After running `brew update` on all casts and formulas, [LicensePlist](https://github.com/mono0926/LicensePlist/releases) version is 3.25.1. @mutaben and me have it now on our developer devices.
- Update the LicensePlist result file.
=> Update LicensePlist version

docs/CONTRIBUTING.md, docs/README.md, hooks/commit-msg
For the internal SRGSSR project tool, Jira, and its deployment feature, the commit message must includes Jira issue id.
SRF colleagues uses it since years, with including in the branch name, the jira issue id.
It's follow the Jira environment mapping configuration introduction, with #452.
This PR proposes to add a `commit-msg` git hook to append Jira issue id into commit message.
ℹ️ The commit messages in this PR were done with this new `commit-msg` git hook 😇
- Add git `commit-msg` hook to modify commit message if the jira issue id exist in the branch name.
- The format is adapted to a simple one: “JIRA-KEY Original commit message”.
- Nice documentations update about required command-lines tools, thanks to @mutaben new contributions.
- Add mention about the internal Jira SRGSSR project. …
=> Git hook to append Jira issue key (PLAYRTS-5503)

docs/CUSTOM_URLS_AND_UNIVERSAL_LINKS.md
#439 switched connection of non-production builds to Play web staging domain.
The documentation was not updated throw.
This PR proposes to update and improve the documentation.
- Update `CUSTOM_URLS_AND_UNIVERSAL_LINKS.md`.
- Mention of Play web stating instead of Play MMF for test purposes.
- Improve the how to test steps.
=> Update Universal Link documentation

Application/Resources/Apps/Play RSI/it.lproj/Localizable.strings, Application/Resources/Apps/Play RTR/rm.lproj/Localizable.strings, Application/Resources/Apps/Play RTS/fr.lproj/Localizable.strings, Application/Resources/Apps/Play SRF/de.lproj/Localizable.strings, Application/Resources/Apps/Play SWI/en.lproj/Localizable.strings, Application/Sources/Content/PageViewController.swift, Translations/Localizable.strings
Following #479 , a test when a content page is not avaible, the error message on iOS was too technical.
The PR propose to use same user error message as used in deep links.
| Currently  | Proposition |
| ------------- | ------------- |
|  ![Banner error message - before](https://github.com/SRGSSR/playsrg-apple/assets/380522/32d5f8ea-f80f-4eb4-bf99-0ff8ae8187cd) | ![Banner error message - after](https://github.com/SRGSSR/playsrg-apple/assets/380522/1810ce10-279b-4ef7-991a-10fcb12353ed) |
Code path to test: [Test swimlane page link not found.patch](https://github.com/SRGSSR/playsrg-apple/files/15355520/Test.swimlane.page.link.not.found.patch)
- Update banner error message with page section link to micro page can't be loaded.
- Update translation files, according to.
=> Improve error message (PLAYRTS-5527)

fastlane/Fastfile
When Xcode 15 pushed a build phases reorder (#374) to have the custom icons, a risk reappeared again to not have a clean repository during a build issue.
The issue came again because of a [tvOS build issue](https://github.com/SRGSSR/playsrg-apple/commit/e92cdfbb0dabeb6e49e2c4ef445e37b5bd461a31): https://github.com/SRGSSR/playsrg-apple/deployments/playsrg-tvos-nightly%2BPLAYRTS-5527-swimlane-link-to-micropage
The copied original application icons [are not removed](https://playcity.eu.ngrok.io/buildConfiguration/playsrgios_NightliesTvOS/443707?buildTab=log&linesState=138&logView=flowAware&focusLine=245):
```
16:25:53   Uncommitted changes:
16:25:53   ?? OriginalAppIcon.appiconset/
16:25:53   ?? OriginalAppStoreTVIcon.appiconset/
16:25:53   ?? OriginalTVAppIcon.appiconset/
```
This PR …
=> CI: clean untracked files when an error occurred

Application/Sources/Content/SectionShowHeaderView.swift, Application/Sources/Content/ShowHeaderView.swift, Application/Sources/Content/ShowHeaderViewModel.swift, Application/Sources/Helpers/Colors.swift, Application/Sources/Helpers/Extensions/UIColor+PlaySRG.swift, Application/Sources/Model/FeaturedContent.swift, Application/Sources/Player/MediaPlayerViewController.m, Application/Sources/Player/ProgramTableViewCell.m, Application/Sources/ProgramGuide/ProgramView.swift, Application/Sources/UI/Views/FeaturedContentCell.swift, Application/Sources/UI/Views/MediaVisualView.swift, Application/Sources/UI/Views/ShowButton.swift, Application/Sources/UI/Views/ShowCell.swift, Application/Sources/UI/Views/ShowCellViewModel.swift, Application/Sources/UI/Views/ShowVisualView.swift, PlaySRG.xcodeproj/project.pbxproj
After some refactoring, we discovered that image not in 16:9 ratio don't have background anymore on iOS, or the default card buttons on tvOS. Let's fix it.
- Add black background on media images for iOS and tvOS.
- ~Use same gray show image background on tvOS as iOS.~
- Introduce `ShowVisualView` to apply also a black background on show images for iOS and tvOS.
=> Fix cell image background (PLAYRTS-5510)

Application/Resources/Apps/Play RSI/ApplicationConfiguration.json, Application/Resources/Apps/Play RTR/ApplicationConfiguration.json, Application/Resources/Apps/Play RTS/ApplicationConfiguration.json, Application/Resources/Apps/Play SRF/ApplicationConfiguration.json, Application/Resources/Apps/Play SWI/ApplicationConfiguration.json, docs/REMOTE_CONFIGURATION.md
From a user feedback, the "resume playback " swimlane contains too much videos and audios which look finished.
The PR proposes to switch to 7% instead of 2%, after weeks of tests.
It also fix missing documentation.
- Update local configuration json files.
- Update remote configuration documentation.
=> PLAYRTS-5528 Update playback end tolerance

Application/Sources/UI/Views/FeaturedContentCell.swift, Application/Sources/UI/Views/FeaturedDescriptionView.swift
Following #493, minors typo updates.
- Add the same long label for previews.
- Run Xcode "Run Structure / Re-indent".
=> PLAYRTS-5553 Improve SwiftUI previews

Application/Sources/Content/Content.swift
**As** a user
**I want to** easily find the show i’m looking for in Show AZ view
**So that** display show items in portrait with title. So the search is easier.
- In the TV show AZ view, switch show cells layout from poster to default 16:9 image variant with displayed title.
=> PLAYRTS-5521 Use 16:9 images in alphabetical TV shows view

Application/Sources/Content/Content.swift, Application/Sources/Content/PageViewController.swift, Application/Sources/Content/PageViewModel.swift, Application/Sources/UI/Views/HighlightCell.swift
**As** a user
**I want to** play the media highlight content with less tap/click if only one editorialised media in
**so that** I don’t ask myself with this highlight detail page exists with only one content.
- A section could have an highlighted item now.
- If this section as only 1 item, it's the highlighted.
- `PageViewController` displays the media player page if the highlighted is a media.
=> PLAYRTS-5562 Open player if media highlight section as only one media

Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt, Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist, PlaySRG.xcodeproj/project.pbxproj, PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
Open a VOD with DRM published with the new stream packaging SRGSSR solution, like [In her car - Deux soeurs - Bicanal (Episode 1/10 - Saison 1) - Play RTS](https://www.rts.ch/play/tv/redirect/detail/14714861)  or  [Top Models - 9263 - Play RTS](https://www.rts.ch/play/tv/top-models/video/9263?urn=urn:rts:video:15043155) (mostly all VOD with DRM in RTS Series topic).
The playback didn’t start at the beginning, but somewhere in the stream
The playback must starts at position 0.0 for VoD and AoD if no saved position in the user history (user data history). 
- Update SRGMediaPlayer to [7.2.3](https://github.com/SRGSSR/srgmediaplayer-apple/releases/tag/7.2.3) which mitigates startup issue with malformed on-demand streams containing misaligned timestamps
- EDIT: SRGMediaPlayer to …
=> PLAYRTS-5595 Mitigate start position for DRM VODs

Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt, Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist, PlaySRG.xcodeproj/project.pbxproj, PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
The calendar view on episode by date, used on audio homepages, the week days started on Sunday on any locale.
In Europe, the first week days is usually Monday. 
- Update to latest [SRGDataProvider 19.0.6](https://github.com/SRGSSR/srgdataprovider-apple/releases/tag/19.0.6) which fix the first weekly day, based on device locale.
=> PLAYRTS-5603 iOS audio calendar view fix

Application/Resources/Apps/Play RSI/it.lproj/Localizable.strings, Application/Resources/Apps/Play RTR/rm.lproj/Localizable.strings, Application/Resources/Apps/Play RTS/fr.lproj/Localizable.strings, Application/Resources/Apps/Play SRF/de.lproj/Localizable.strings, Application/Resources/Apps/Play SWI/en.lproj/Localizable.strings, Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt, Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist, Application/Sources/Calendar/CalendarViewController.m, Application/Sources/Content/Content.swift, Application/Sources/Content/PageViewController.swift, Application/Sources/Content/PageViewModel.swift, Application/Sources/Content/SectionViewController.swift, Application/Sources/UI/Views/ShowAccessCell.swift, PlaySRG.xcodeproj/project.pbxproj, PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved, TV Application/Sources/SceneDelegate.swift, Translations/Localizable.strings
This PR proposes an internal test only for audios tab, following #487 with two new supported sections:
- show access (with only the first radio channel for now)
- continue hearing section.
- For all (public and beta): update section translations for SRF ("resume video playback" and "resume audio playback").
- Connect show access section to audio content.
- Only first radio channel for A to Z page if it's the landing PAC audio page.
- Only first radio channel for show by date page if it's the landing PAC audio page.
- Use the calendar icon for audio pages.
-  Add audio resume playback section support (Continue hearing). https://github.com/SRGSSR/srgdataprovider-apple/pull/68
- For all (public and beta): update section translations for SRF ("resume video playback" and "resume audio …
=> PLAYRTS-5541 Beta only audio content pages with new section types

Application/Sources/UI/Helpers/MediaDescription.swift
**As** an audio user
**I want to** know from which show an episode is from, in the “by date” view
**so that** I can select better what I would like to listen.
Display show title in audio episodes by date if not redundant with media title.
The show title is displayed after the media published time with a medium point between “media.formattedTime · show.title”.
> [!TIP]
> Same comparaison in an existing media description representation:
> -  Using: `areRedundant(media: SRGMedia, show: SRGShow) -> BOOL`
> - "not redundant with media title": check with `title` and `subtitle` media description properties the the show title is not displayed twice.
- Add show title in the `subtitle` media description string, if not redundant for `MediaDescription.Style.time` case.
- Refactor the `subtitle` logic …
=> PLAYRTS-5605 Show title in audios by date

fastlane/gh-pages/deployments/build.html
Following #498, an unexpected Github page link is still displayed: On the deployment page, Play SWI link.
Example: https://srgssr.github.io/playsrg-apple/deployments/build.html?configuration=Nightly&platform=iOS&version=3.8.8-541+PLAYRTS-5578-ios18-update
- Remove Play SWI in Github deployment page code generator.
=> PLAYRTS-5584 Remove Play SWI link in deployment pages

UITests/Screenshots/Sources/ApplicationScreenshots~ios.swift, UITests/Screenshots/Sources/ApplicationScreenshots~tvos.swift, docs/RELEASE_CHECKLIST.md, fastlane/Fastfile, fastlane/README.md
Like SRF marketing team, RTS marketing takes care of the AppStore detail page, and its previews and screenshots.
In the fastlane scripts, remove the "upload" step, to avoid erasing the current screenshots.
- Fix iOS and tvOS screenshots builds.
- Remove `upload_screenshots(platform)` for RTS screenshots lanes.
- Running in Xcode the screenshots targets have a build success.
- Running locally in Terminal.app ` creates the expected screenshots images from the target in the repository folder `fastlane/export` but not upload anymore on AppStore Connect the new screenshots:
- `bundle exec fastlane iOS tvOSrtsScreenshots` for RTS tvOS screenshots.
- `bundle exec fastlane iOS iOSrtsScreenshots` for RTS iOS screenshots.
⚠️ Running SRF variants also don't upload new screenshots. But running RSI or …
=> PLAYRTS-5538 Update RTS AppStore screenshots workflow

fastlane/Fastfile
Build from the `main` branch must not have the "main" build name.
It's a regression from #515 workflow modification.
- Fix the build name and avoid `main` in build name and version suffix from the main branch.
=> PLAYRTS-500 Fix build name on main branch

.github/workflows/check-pr-labels.yml, docs/GITHUB_ENVIRONMENTS_AND_DEPLOYMENTS.md, docs/WORKFLOWS.md
The workflow documentation mentionnes to add a label to any PR, to help tag release notes.
A GitHub Action can check that allowed labels are used.
- Add a new GitHub action, which read allowed labels from `.github/release.yml` and compare with the labels on PR.
- Update documentation to mentioned GitHub actions.
=> PLAYNEXT-500 Check pull request labels

docs/CONTRIBUTING.md, docs/README.md, docs/WORKFLOWS.md, fastlane/Fastfile, fastlane/README.md
Following #515 , the AppStore release workflow can be improved, as it's not on a release branch or `master` branch anymore, but the `main` branch. Automation and easier CI UI usage.
- Allow on CI UI to set the `tag_version` to release.
- Add Github action to check labels on opened PR.
- Improve scheduled fastlane "AppStore Status" to run "publish release notes" automatically when a new AppStore release is published.
- Improve workflow documentation.
- Add table of content for `readme.md` and `workflows.md`.
=> PLAYNEXT-500 Improve release workflow

Application/Sources/UI/Helpers/MediaDescription.swift, Application/Sources/UI/Views/HeroMediaCell.swift
In PAC, the Play CMS, editors can update media title and lead. If the media title is set to the show title, the current logic is to displays only the date. In the hero stage, it's no correct anymore, from an UX point of view.
If the media title contains the show title, Play web does not display the show title, which is correct, from an UX point of view.
Play web does not display the media published date anymore.
- Add `title` style for `MediaDescription`, to avoid displaying date, in subtitles but alors in title.
- Update `areRedundant(media:, show:)` like Play web implementation.
=> PLAYNEXT-832 Fix hero stage title and subtitle

Application/Application-Info.plist
ITMS reported this issue:
> Hello,
> 
> We noticed one or more issues with a recent delivery for the following app:
> 
> Play SRF: Streaming TV & Radio
> Version 3.8.9
> Build 461
> Although delivery was successful, you may want to correct the following issues in your next delivery. Once you've corrected the issues, upload a new binary to App Store Connect.
> 
> ITMS-90899: Macs with Apple silicon support issue - The app isn‘t compatible with the provided minimum macOS version of 11.0. It can run on macOS 12.0 or later. Please specify an LSMinimumSystemVersion value of 12.0 or later in a new build, or select a compatible version in App Store Connect. For details, visit: https://developer.apple.com/help/app-store-connect/manage-your-apps-availability/manage-availability-of-iphone-and-ipad-a …
=> PLAYNEXT-1020 Add MacOS minimum OS version

Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt, Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist, PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
The SRG Analytics team asked an analytics update:
See https://github.com/SRGSSR/srganalytics-apple/releases/tag/9.1.5
- Update `SRGAnalytics` to from 9.14. to [9.1.5](https://github.com/SRGSSR/srganalytics-apple/releases/tag/9.1.5).
No custom comScore info are set in `SRGAnalyticsPageViewLabels`, so no change to do.
=> Update SRGAnalytics to 9.1.5

Application/Resources/Apps/Play RSI/ApplicationConfiguration.json, Application/Resources/Apps/Play RTR/ApplicationConfiguration.json, Application/Resources/Apps/Play RTS/ApplicationConfiguration.json, Application/Resources/Apps/Play SRF/ApplicationConfiguration.json, Application/Resources/Apps/Play SWI/ApplicationConfiguration.json, Application/Sources/Configuration/ApplicationConfiguration.h, Application/Sources/Configuration/ApplicationConfiguration.m, Application/Sources/Settings/Service.swift, docs/REMOTE_CONFIGURATION.md
To decide if we would like this hot fix and expedite review by Apple.
- Add an optional remote configuration property to override DataProdvider service url, named `serviceURL`.
=> Add remote configuration service url

Application/Sources/Application/AppDelegate.m, Application/Sources/Application/SceneDelegate.m, Application/Sources/Settings/ApplicationSettings+Common.m, Application/Sources/Settings/ApplicationSettingsConstants.h, Application/Sources/Settings/ApplicationSettingsConstants.m, Application/Sources/Settings/ProxyDetection.swift, Application/Sources/Settings/SettingsView.swift, Application/Sources/Settings/UserDefaults+ApplicationSettings.swift, PlaySRG.xcodeproj/project.pbxproj, TV Application/Sources/AppDelegate.swift, TV Application/Sources/SceneDelegate.swift, Translations/Localizable.strings
SRG Legal department asked to implement on the server side, a VPN or Proxy detection, for some protected content.
To test, a debug setting can be added to add a query parameter `forceProxyDetection`. 
[SRGDataProvider 19.0.10](https://github.com/SRGSSR/srgdataprovider-apple/releases/tag/19.0.10) has a new block reason, already updated with #557 .
- Add "VPN or Proxy detection" option in advanced settings section, iOS and tvOS, with the new hidden query parameters `forceProxyDetection` ([VPNORPROXY](https://il-stage.srgssr.ch/integrationlayer/2.0/mediaComposition/byUrn/urn:rts:video:3608517?forceProxyDetection=VPNORPROXY) or [DIRECT](https://il-stage.srgssr.ch/integrationlayer/2.0/mediaComposition/byUrn/urn:rts:video:3608517?forceProxyDetection=DIRECT)).
- Save in User Defaults.
- Reload …
=> PLAYNEXT-3096 Add VPN or Proxy detection settings

Application/Resources/Apps/Play RSI/it.lproj/Localizable.strings, Application/Resources/Apps/Play RTR/rm.lproj/Localizable.strings, Application/Resources/Apps/Play RTS/fr.lproj/Localizable.strings, Application/Resources/Apps/Play SRF/de.lproj/Localizable.strings, Application/Resources/Apps/Play SWI/en.lproj/Localizable.strings, Application/Sources/Content/Content.swift, Application/Sources/Settings/ProxyDetection.swift, Translations/Localizable.strings
When changing the Emissions section title on the Audio tab homepage, it changed on Videos tab as well because the same wording key was used.
Split the section title getter to handle the Videos and Audio differently.
<div>
</div>
=> [PLAYNEXT-3121] Fix Shows section title on Videos tab homepage

Application/Sources/UI/Views/HeroMediaCell.swift
When enabling Audio Curation for RTR and SRF, the Hero Stage uses 16:9 image instead of the 1:1 one.
Force usage of media image for Hero Stage instead of the podcast show image
=> PLAYNEXT-3294 Fix hero image
