SRGSSR/playsrg-apple

- Application/Sources/Player/MediaPlayerViewController+Private.h
- Application/Sources/Player/MediaPlayerViewController.m
- Application/Sources/Player/MediaPlayerViewController.storyboard
Don't create unnecessary letterbox controller, which also help to check allocations with Instruments.
Resoles #220 
> Create Letterbox controller only if necessary

- Application/Sources/CarPlay/CarPlayList.swift
- Application/Sources/CarPlay/CarPlayTemplateListController.swift
- Application/Sources/Content/PageViewController.swift
- Application/Sources/Content/Publishers.swift
- Application/Sources/Helpers/Accessibility.swift
- Application/Sources/Helpers/Signals.swift
- Application/Sources/Settings/SettingsViewModel.swift
- Application/Sources/UI/Views/DownloadCellViewModel.swift
- TV Application/Sources/AppDelegate.swift
- TV Application/Sources/LetterboxDelegate.swift
> Avoid notification center publisher leaks

- Application/Sources/Model/Download.h
- Application/Sources/Model/Download.m
Following #230 PR closed a bit quickly to send for external testing.
Thank you to @defagos for the review in #230 
> Cleanup download code

- Application/Sources/Player/MediaPlayerViewController.m
Resolves #240 
It's a regression on iOS 16 release.
-  [ ] `swiftlint` has run to ensure the *Swift* code style is valid.
-  [ ] `rubocop -a` has run to ensure the *Ruby* code style is valid.
> Full screen player when opened from the program guide

- Application/Sources/Helpers/AnalyticsConstants.h
- Application/Sources/Helpers/AnalyticsConstants.m
- Application/Sources/ProgramGuide/ProgramViewModel.swift
- PlaySRG.xcodeproj/project.pbxproj
- PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
> TV guide program tracking update

- Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
- Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist
- PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
Continuous updates to follow third party libraries.
- Aiolos (modal view for song list)
- swift-protobuf
- ios-library (Airship)
- FLEX (debug tool)
- firebase
> Update third party libraries

- Application/Resources/Apps/Play RTR/rm.lproj/Accessibility.strings
- Application/Resources/Apps/Play RTR/rm.lproj/InfoPlist.strings
- Application/Resources/Apps/Play RTR/rm.lproj/Localizable.strings
- Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
- Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist
- Application/Sources/ProgramGuide/ChannelHeaderView.swift
- Application/Sources/ProgramGuide/LoadingCell.swift
- Application/Sources/ProgramGuide/ProgramCell.swift
- Application/Sources/ProgramGuide/ProgramGuideGridLayout.swift
- Application/Sources/ProgramGuide/ProgramGuideViewController.swift
- Application/Sources/ProgramGuide/ProgramView.swift
- Application/Sources/ProgramGuide/ProgramViewModel.swift
- Application/Sources/Settings/ApplicationSettings+Common.h
- Application/Sources/Settings/ApplicationSettings+Common.m
- PlaySRG.xcodeproj/project.pbxproj
- PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
- fastlane/Fastfile
Following #239.
- Need to display more content on the grid layout.
- First app launch on the list layout for compact screen width.
- Calendar event created has more information in the notes section. 
> TV guide program iteration and grid layout update

- Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
- Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist
- PlaySRG.xcodeproj/project.pbxproj
- PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
Major update.
After successful tested, use it. 
> Update Firebase dependency

- Application/Sources/Application/SceneDelegate.m
- Application/Sources/Helpers/AnalyticsClickEvent.swift
- Application/Sources/Helpers/Categories/NSDateFormatter+PlaySRG.h
- Application/Sources/Helpers/Categories/NSDateFormatter+PlaySRG.m
- Application/Sources/ProgramGuide/ProgramGuideHeaderView.swift
- Application/Sources/UI/Views/CalendarView.swift
Add missing date selection metrics, according to Play web definition.
- Add metrics.
- Start property clarification in the code. 
> Program guide metrics 2

- Application/Sources/ProgramGuide/ProgramGuideListViewController.swift
Resolves #262 , reported by @svenduvoisin.
> Fix program guide list layout update

- fastlane/Fastfile
Follow Xcode and iOS/tvOS releases.
> Build project with Xcode 14.2.x

- Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
- Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist
- PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
Always try to be with latest version of third party libraires.
- Update patch dependencies
- Firebase to 10.3.0
> Update Firebase minor update and libraries fixies

- Application/Sources/Content/PageViewController.swift
- Application/Sources/Content/PageViewModel.swift
> Content page id in page view event

- fastlane/Fastfile
After signing commits, sign also tags
Add the sign property to fastlane action `add_git_tag`.
> CI: Sign tags

- .github/PULL_REQUEST_TEMPLATE.md
- .rubocop.yml
- .swiftlint.yml
- Gemfile
- Gemfile.lock
- Makefile
- Scripts/check-quality.sh
- Scripts/fix-quality.sh
- docs/CONTRIBUTING.md
- hooks/pre-commit
The PR template has code style checkboxes.
Inspired by Pillarbox Apple CI (https://github.com/SRGSSR/pillarbox-apple/pull/197 and https://github.com/SRGSSR/pillarbox-apple/pull/230), we can automate those steps.
- Add `check-quality.sh` script, including `swiftlint`, `rubocop`, `shellcheck`, `yamllint`.
- Add an optional  pre-commit hook for developers and contributors.
- Update MakeFile with new action parameters.
- Update pull request template accordingly.
- Update contributing documentation accordingly.
Related to this PR:
- On the project "PlayCity" CI, check quality is enabled.
- On GitHub protected branch, status check is enabled.
-  [x] …
> Check code quality

- Application/Resources/Apps/Play RTS/fr.lproj/Localizable.strings
- Application/Resources/Apps/Play SRF/de.lproj/Localizable.strings
- WhatsNew-iOS-beta.json
- WhatsNew-tvOS-beta.json
New betas, pre-releases.
- Play iOS 3.6.12-411
- Play tvOS 1.6.10-60
> Prepare beta releases

- Application/Resources/Apps/Play RSI/it.lproj/Localizable.strings
- Application/Resources/Apps/Play RTR/rm.lproj/Localizable.strings
Updated translations from translator colleagues.
- Update internal beta translations.
> Update Italian and romansh translations

- Application/Sources/Model/Onboarding.swift
- Application/Sources/Settings/Service.swift
**As a developer**, I aim to ensure that my code passes the quality check using SwiftLint 0.52.4.
Self-explanatory.
> Fix quality check with SwiftLint 0.52.4

- Application/Resources/Apps/Play RSI/it.lproj/Localizable.strings
Sport livestreams translations improved for Play RSI.
- Update Italian translations.
> Update Italian translations

- Makefile
SRG SSR online and digital teams migrated to Jira Cloud.
- Update private configuration with new Jira url, used in published beta release notes on Slack.
> Update configuration with new Jira url

- PlaySRG.xcodeproj/xcshareddata/xcschemes/Play RSI TV screenshots.xcscheme
- PlaySRG.xcodeproj/xcshareddata/xcschemes/Play RSI TV.xcscheme
- PlaySRG.xcodeproj/xcshareddata/xcschemes/Play RSI screenshots.xcscheme
- PlaySRG.xcodeproj/xcshareddata/xcschemes/Play RSI.xcscheme
- PlaySRG.xcodeproj/xcshareddata/xcschemes/Play RTR TV screenshots.xcscheme
- PlaySRG.xcodeproj/xcshareddata/xcschemes/Play RTR TV.xcscheme
- PlaySRG.xcodeproj/xcshareddata/xcschemes/Play RTR screenshots.xcscheme
- PlaySRG.xcodeproj/xcshareddata/xcschemes/Play RTR.xcscheme
- PlaySRG.xcodeproj/xcshareddata/xcschemes/Play RTS TV screenshots.xcscheme
- PlaySRG.xcodeproj/xcshareddata/xcschemes/Play RTS TV.xcscheme
- PlaySRG.xcodeproj/xcshareddata/xcschemes/Play RTS screenshots.xcscheme
- PlaySRG.xcodeproj/xcshareddata/xcschemes/Play RTS.xcscheme
- PlaySRG.xcodeproj/xcshareddata/xcschemes/Play SRF TV screenshots.xcscheme
- PlaySRG.xcodeproj/xcshareddata/xcschemes/Play SRF TV.xcscheme
- PlaySRG.xcodeproj/xcshareddata/xcschemes/Play SRF screenshots.xcscheme
- PlaySRG.xcodeproj/xcshareddata/xcschemes/Play SRF.xcscheme
- PlaySRG.xcodeproj/xcshareddata/xcschemes/Play SWI TV screenshots.xcscheme
- PlaySRG.xcodeproj/xcshareddata/xcschemes/Play SWI TV.xcscheme
- PlaySRG.xcodeproj/xcshareddata/xcschemes/Play SWI screenshots.xcscheme
- PlaySRG.xcodeproj/xcshareddata/xcschemes/Play SWI.xcscheme
Following #418, Xcode proposed a project update.
- Update to Xcode 15.2 the project bundle.
> Update Xcode project to Xcode 15.2

- .jira/config.yml
Following Play web project, let's try to share deployment to the project tool.
- Add Jira configuration file.
> Add Jira environment mapping configuration

- .github/release.yml
- .github/workflows/pr-closure.yml
- .jira/config.yml
- .rubocop.yml
- .swiftlint.yml
- .yamllint.yml
- Scripts/check-quality.sh
Following #452 , update check yaml command.
https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
- Update `check-quality.sh`.
- Update `.yml` files.
> Update yaml lint rules and files

- Application/Sources/Helpers/SupportInformation.swift
[Users recently reported](https://srgssr-ch.atlassian.net/browse/SMAC-483334) playback issues which could only reproduced with subtitles enabled.
To help us better understand the context associated with a reported issue, this PR adds audio and subtitle selection information to support information that can be sent to us.
Self-explanatory.
> Add audio and subtitle selection to support information (PLAYRTS-5498)

- Application/Resources/Settings.bundle/com.mono0926.LicensePlist/ios-library.plist
Running `license-plist` updated the AirShip license. Update it.
- AirShip license updated.
> Update Airship license

- Application/Resources/Apps/Play RTR/rm.lproj/Localizable.strings
- Translations/Accessibility.strings
- Translations/Localizable.strings
An update romach translation was asked.
- Update romansh translations.
- Update `genstrings` output files on first line.
> Update romansh translation

- Application/Sources/Content/Content.swift
- Application/Sources/Helpers/UserConsentHelper.swift
Updating `swiftlint` to [version 0.55.1](https://github.com/realm/SwiftLint/releases/tag/0.55.1) introduced new lint warnings.
The PR proposes to update swift code and pass lint tests.
- Remove unnecessary `self`.
- Remove unnecessary var definitions.
> Fix linter with SwiftLint 0.55.1

- Scripts/check-quality.sh
> error: File not found at /Users/[user]/Developer/playsrg-apple/TV.
This PR fixes "TV Appplications" `swiftformat` running mentioned issue.
- In the command line scripts: enclose the folder paths in double quotes.
> Fix only-changes check quality script

- Application/Sources/UI/Controllers/TabBarController.m
Following #523, adding also the satellite radio for Play RTS.
- Fix the radio channels count to display the radio channel tab bar.
> PLAYNEXT-1192 Fix satellite radios discoverability for Play RTR

- docs/RELEASE_CHECKLIST.md
Steps have changed. Update the release workflow checklist.
- Remove skipped steps.
- Clarify Private betas steps, as it's linked to AppStore build.
> Update release workflow documentation

- Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
- Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist
- PlaySRG.xcodeproj/project.pbxproj
- PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
- WhatsNew-iOS-beta.json
- WhatsNew-tvOS-beta.json
Update librairies 
Update SRGDataProvider
Update SRG-appearance
> [PLAYNEXT-3091] Update librairies

- Application/Sources/Content/PageViewController.swift
The CMS PAC introduced section detail and micro page links on the highlight section.
It was already supported for tvOS but not for iOS.
This PR fixes it. 
- Refactor the "Open section page" logic in one place for iOS.
- Clean `SectionHeaderViewAction` extension (of `PageViewController`), with only the declared method.
- Add support for micro page link (content link) with Highlight and More items.
Can be tested with: https://play-web.herokuapp.com/srf/stage/play/tv (Play SRF stage)
Copy and past this url in the deeplink tool to get the scheme url you would like: https://play-mmf.herokuapp.com/deeplink/index.html
> PLAYNEXT-3425 Support micropage link on iOS highlight items

- Application/Resources/Apps/Play RSI/ApplicationConfiguration.json
- Application/Resources/Apps/Play RSI/it.lproj/Localizable.strings
- Application/Resources/Apps/Play RTR/ApplicationConfiguration.json
- Application/Resources/Apps/Play RTR/rm.lproj/Localizable.strings
- Application/Resources/Apps/Play RTS/ApplicationConfiguration.json
- Application/Resources/Apps/Play RTS/fr.lproj/Localizable.strings
- Application/Resources/Apps/Play SRF/ApplicationConfiguration.json
- Application/Resources/Apps/Play SRF/de.lproj/Localizable.strings
- Application/Resources/Apps/Play SWI/ApplicationConfiguration.json
- Application/Resources/Apps/Play SWI/en.lproj/Localizable.strings
- Application/Sources/Application/Navigation.swift
- Application/Sources/Configuration/ApplicationConfiguration.h
- Application/Sources/Configuration/ApplicationConfiguration.m
- Application/Sources/Configuration/ApplicationConfiguration.swift
- Application/Sources/Configuration/ApplicationSection.h
- Application/Sources/Configuration/ApplicationSection.m
- Application/Sources/Helpers/ApplicationSectionInfo.m
- Application/Sources/Helpers/SupportInformation.swift
- Application/Sources/Profile/ProfileHelp.swift
- Application/Sources/Profile/ProfileViewController.m
- Application/Sources/Settings/SettingsView.swift
- Application/Sources/Settings/SettingsViewModel.swift
- PlaySRG.xcodeproj/project.pbxproj
- TV Application/Sources/SupportFormView.swift
- Translations/Localizable.strings
- docs/REMOTE_CONFIGURATION.md
Replace old support type form with new one, adding more parameters to it.
- Create new remote config URL
- Remove old one
- Remove contact address mail
- Add new router method to navigate to QR code screen
> PLAYNEXT-2925 PLAYNEXT-2927 Support form
